### ISSUE TITLE
如何运行这代码？

### ISSUE THREAD

**Issue by Hardold** [mcximing/sort-cpp#1]
您好！
     非常感谢您写的代码，想请教一个问题，如何运行您的代码？能指导一下吗？

**Comment by mcximing** [comment]
你好。在data文件夹里附有视频序列的目标检测结果，用于算法输入，运行代码时只要顺利编译运行应该就可以输出结果，结果在output文件夹里，是文本形式，依照MOT Challenge 2015的格式，可以直接用他们的代码进行评估。
如果想要在视频上查看跟踪轨迹效果，可到MOT基准测试集网站 https://motchallenge.net/data/2D_MOT_2015/ 下载数据集，然后自行编写一点代码将跟踪轨迹显示在连续播放的图像序列上。相信这个不难做到哈！

**Comment by Hardold** [comment]
您好！数据集已经下载了，程序已经跑起来了，显示跟踪的速度可以达到800-1000fps,难以置信？如果是这样，速度真是太棒了！还有一个问题，跟踪轨迹显示实现的思路是怎样的？代码加到哪里比较合适？希望能指点一二。

**Comment by Hardold** [comment]
您好，我实现了跟踪轨迹，但是实现出的效果不好。加入的代码如下图所示：
![traces](https://cloud.githubusercontent.com/assets/12985844/18781963/9ecc5f1a-81b6-11e6-9760-88d850f90261.png)
`// Update the state vector with observed bounding box.
void KalmanTracker::update(StateType stateMat)
{
    m_time_since_update = 0;
    m_history.clear();
    m_hits += 1;
    m_hit_streak += 1;

```
// measurement
measurement.at<float>(0, 0) = stateMat.x + stateMat.width / 2;
measurement.at<float>(1, 0) = stateMat.y + stateMat.height / 2;
measurement.at<float>(2, 0) = stateMat.area();
measurement.at<float>(3, 0) = stateMat.width / stateMat.height;

// update
Mat s = kf.correct(measurement);

//  std::vector<cv::Point_<float>> trace;
//-------实现轨迹跟踪--------------

if (trace.size() > 10)
{
    trace.erase(trace.begin(), trace.end() - 10);
}

cv::Point_<float> result;

result.x = s.at<float>(0, 0);

result.y = s.at<float>(1, 0);

trace.push_back(result);
//----------------------------
```

}`

**Comment by Hardold** [comment]
`// Update the state vector with observed bounding box.
void KalmanTracker::update(StateType stateMat)
{
	m_time_since_update = 0;
	m_history.clear();
	m_hits += 1;
	m_hit_streak += 1;

	// measurement
	measurement.at<float>(0, 0) = stateMat.x + stateMat.width / 2;
	measurement.at<float>(1, 0) = stateMat.y + stateMat.height / 2;
	measurement.at<float>(2, 0) = stateMat.area();
	measurement.at<float>(3, 0) = stateMat.width / stateMat.height;

	// update
	Mat s = kf.correct(measurement);

	//	std::vector<cv::Point_<float>> trace;
	//-------实现轨迹跟踪--------------

	if (trace.size() > 10)
	{
		trace.erase(trace.begin(), trace.end() - 10);
	}

	cv::Point_<float> result;

	result.x = s.at<float>(0, 0);

	result.y = s.at<float>(1, 0);

	trace.push_back(result);
	//----------------------------
	
}`

**Comment by Hardold** [comment]
跟踪轨迹实现后的效果，跟踪线有锯齿。有建议吗？
![tracesline](https://cloud.githubusercontent.com/assets/12985844/18782701/42f45f2c-81ba-11e6-9709-c64dbcb91154.png)
![tracesline2](https://cloud.githubusercontent.com/assets/12985844/18782702/42fa305a-81ba-11e6-99ee-146c7b74e281.png)

**Comment by mcximing** [comment]
你好。见信晚了，看到你已经搞定了轨迹显示，祝贺啊！至于轨迹线有锯齿，我觉得应该是由于检测结果不稳定导致的。现在学术界做的多目标跟踪大多是基于现成的目标检测结果，输入每一帧的检测框，通过关联求解每个目标各自的轨迹。这个代码也是做的这一步，因此得出的轨迹等于直接将各帧的检测中心连起来，而检测结果是互相独立的，所以锯齿恐怕难以避免，不过如果不要求精确，可以考虑输出时用中值滤波之类平滑一下坐标的吧，但这样似乎就不是实时画图了。这个我没有实验过，只是想法哈。
另外跟踪速度挺快，也是由于使用现成检测结果的原因，毕竟只是做了帧间关联嘛。卡尔曼滤波和匈牙利算法也没太大计算量。不过算法思想不是我的，我只是复现而已，具体请参见https://github.com/abewley/sort ，及其作者论文。据我所知此文已经发表在ICIP2016上了。
以上说的有什么不对的地方请包涵指正~

**Comment by ZeyuFu** [comment]
能问一下楼主如何用那个motchallenge_devkit 啊，那个test data 不都是没有ground_truth 的吗？那怎么评价跟踪结果呢？

**Comment by mcximing** [comment]
嗯，MOT Challenge 2015的数据集分为训练集和测试集，而测试集确实没有ground truth，所以只能将结果上传到他们的网站去评估。那个motchallenge_devkit的作用是配合下载的训练集数据，那里边有真值标注。evaluateTracking.m有个参数要指定数据集的位置。当然网站也提供训练集真值标注的单独下载。

**Comment by ZhihongChen123** [comment]
你好，请问这个跟踪轨迹图怎么绘制呢，我加入你发的代码，但是还是没有显示出来，请问需要在加入一些别的代码吗？谢谢 @Hardold

**Comment by Tough2011** [comment]
你好，想问下那个测试数据没有ground_truth，上传到哪个网站测试啊@楼主@ZeyuFu

**Comment by mcximing** [comment]
你好，MOT Challenge 2015 的测试集可将结果上传到他们的网站 https://motchallenge.net/ 进行评估。详情请参考网站说明。@mayday501

**Comment by Tough2011** [comment]
您好，我采用yolo+KCF做的MOT，并没有用到MOT16里的训练集。我在用训练集测试的时候，发现效果不对，想问下格式是怎么要求的

在 2018-07-15 15:27:02，"Cong Ma" <notifications@github.com> 写道：


你好，MOT Challenge 2015 的测试集可将结果上传到他们的网站 https://motchallenge.net/ 进行评估。详情请参考网站说明。@mayday501

**Comment by mcximing** [comment]
你好，格式在 MOT16 的论文中有详细说明。请参考论文。网站上有链接：https://arxiv.org/abs/1603.00831 @mayday501

**Comment by sadeqbillah** [comment]
Hello Mcximing: thanks for sharing your nice piece of code. I have one question. If you can guide me will be highly appreciated. The code is using off-the-shelf detection results. Is it possible to use the code directly with IP Camera? I debugged the code but could not find a way to do that. Can you please help?

**Comment by mcximing** [comment]
Hello @sadeqbillah. Thanks for your attention. Yes, this code uses off-the-shelf detection results. If you want to run it with IP camera, I think you need to first run a detection algorithm on the image frames and then use this tracking code to connect the detection results and get the trajectories. The detection part is not contained in this code.

**Comment by holyhao** [comment]
@mcximing hi, thanks for your work. If i use detection then use only use this track method in next 2 seconds ，repeatedly. Does this track works?  Or, it needs detection results and track results every frame?

**Comment by mcximing** [comment]
@holyhao Hi, this tracker is a strictly online method. In other words, it only works on the latest frame. Yes it needs detection results at every frame. But you can add other tracking methods to this framework and implement your idea.

**Comment by holyhao** [comment]
@mcximing I see and tanks for your reply.

**Comment by holyhao** [comment]
@mcximing Hi, sorry to bother you again. I am not so familiar with the KalmanTracker. How does initial parameters stateNum and  measureNum influence the results? Another way, when the video is still，the box is stable engouh. But when the camera move quickly , the box is slow to track. Could you please share some ideas?

**Comment by mcximing** [comment]
@holyhao Hi, the stateNum and measureNum in the KalmanTracker depend on how you model the target motion with Kalman filter. For example, you model the state of the target as (x,y,u,v) and you can observe the measurements (x,y), in this way, stateNum=4 and measureNum=2. They are the motion model parameters. Results are influenced by your model. And since the Kalman filter is a linear model, it is natural that it performs not so well in the case of sudden movements. Maybe my explanation is not so exact. It would be best if you check some tutorials and papers on the Kalman filter.

**Comment by wwdok** [comment]
> 您好！数据集已经下载了，程序已经跑起来了，显示跟踪的速度可以达到800-1000fps,难以置信？如果是这样，速度真是太棒了！还有一个问题，跟踪轨迹显示实现的思路是怎样的？代码加到哪里比较合适？希望能指点一二。

哥们你好，我运行代码后，命令行窗口显示"Image path not found!"，我猜这是因为代码里imgPath设置得不对，但我想知道这个路径里放的是什么图片，是视频每隔几秒得截图吗，这个在网上能下载到吗？谢谢！

**Comment by wwdok** [comment]
> 你好，请问这个跟踪轨迹图怎么绘制呢，我加入你发的代码，但是还是没有显示出来，请问需要在加入一些别的代码吗？谢谢 @Hardold

@Hardold @ZhihongChen123 我在KalmanTracker.cpp里把void KalmanTracker::update(StateType stateMat)这个函数替换掉原来的了，但是视频上还是无法显示轨迹，请问我还少了什么步骤吗？

**Comment by mcximing** [comment]
> 
> 
> > 你好，请问这个跟踪轨迹图怎么绘制呢，我加入你发的代码，但是还是没有显示出来，请问需要在加入一些别的代码吗？谢谢 @Hardold
> 
> @Hardold @ZhihongChen123 我在KalmanTracker.cpp里把void KalmanTracker::update(StateType stateMat)这个函数替换掉原来的了，但是视频上还是无法显示轨迹，请问我还少了什么步骤吗？

他贴的代码是计算中心点位置，你要是想显示轨迹肯定需要在画图的时候cv:line一下啊。
